### ISSUE TITLE
Accessing the --help menu data

### ISSUE THREAD

**Issue by ProfessorManhattan** [jmcdo29/nest-commander#128]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Hey, I am trying to automatically generate a man page since `package.json` has an option for it. How can I access the Commander.js --help menu object from the app? I'd be willing to contribute this in the form of a PR

### Describe the solution you'd like

I'd like to be able to get the menu data in JSON format and from there I can do with it as I please.

Alternatively, I could open a PR and we can integrate this into the schematic but I might have questions.

### What is the motivation / use case for changing the behavior?

For completeness sake, I'd like to have automatically generated man pages for all my CLI apps. I plan on using nest-commander for all of them (hopefully).

**Comment by jmcdo29** [comment]
Does commander normally give you averted to the help menu as a json? I haven't seen that option before.

What is the end goal, just to be able to modify the help output?

**Comment by smolinari** [comment]
My best guess is it's about using the man property in package.json to be able to call up documentation. 

https://docs.npmjs.com/cli/v7/configuring-npm/package-json#man

If it's true, however, I still personally don't understand the need for the extra docs, since to get the docs, the user would have to install the CLI and once the CLI is installed, the user can call up help on any command via the CLI anyway. So, the man pages wouldn't be necessary. 🤷   

Scott

**Comment by jmcdo29** [comment]
As I haven't gotten any extra clarity on this in over a month, I'm going to close it out. If you can provide extra context around what you're attempting to do, we can see what can be done.
