### ISSUE TITLE
Need a way to inject current command (instead of root command)

### ISSUE THREAD

**Issue by hungtcs** [jmcdo29/nest-commander#482]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I noticed that there is a decorator at present named `InjectCommander`, it can inject the root command object.

But sometimes, some functions requires to get the current command object, `command.help()` eg. different commands print different content.

### Describe the solution you'd like

- `@InjectCurrentCommander()`
or
- `@InjectCommander({ current: true })`

### What is the motivation / use case for changing the behavior?

Get current command / sub-command object.

**Comment by hungtcs** [comment]
My current solution is

```typescript
import { Command, CommandRunner, InjectCommander } from 'nest-commander';
import { Command as _Command } from 'commander';

@Command({
  name: 'exec',
  description: '',
})
export class ExecCommand implements CommandRunner {

  constructor(
      @InjectCommander() private readonly commander: _Command) {

  }

  public async run() {
    this.commander.commands.find(command => command.name() === 'exec')?.help();
  }

}
```

**Comment by jmcdo29** [comment]
I'll see if I can figure out some sort of way to implement this soon. Thanks for the suggestion

**Comment by hungtcs** [comment]
@jmcdo29 Yes, for now, I just want to output the help of the current command

**Comment by jmcdo29** [comment]
I think what I'm going to end up doing is adding a `commandInstance` property and making `CommandRunner` an `abstract` class (breaking change) instead of an `intrerface` then setting that value from the `CommandRunnerService` class when creating the command. That way, `this.commandInstance` now points to the current command. As the commands aren't registered in the DI tree, it won't be possible to do `@InjectCommand()` or anything like that, but this should be a decent solution instead
