### ISSUE TITLE
Dependencies on request-scroped providers lead to DI failure

### ISSUE THREAD

**Issue by xydens** [jmcdo29/nest-commander#754]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have a request-scoped service somewhere in ths bottom of the dependencies tree. When I try to inject to my command runner a service, that directly or indirectly injects a request-scoped provider the DI system becomes unpredictable. The most common failure is that the command runner`s constructor is not being called and its dependencies are `undefined`. In some cases the mase behaviour is observed on other providers.
I think it is reasonable that CLI executor can not inject a request - it has not an incoming HTTP request. But the problem is unpredictable DI behaviour without any warnings or errors. It becomes hard to investigate resons of such errors: in our team it took aout 4 months between the first encounter with such error and discovering the reason. 

### Minimum reproduction code

https://github.com/xydens/nest-commander-mrr-0 this is the reproduction repo.
1. `yarn install`
2. `yarn build`
3. `node dist/cli.js articles:publish-delayed`

You will see:
```
/nest-commander-bug-example-0/dist/domain/articles/publish-delayed-articles.command.js:28
            const authorGrants = this.grantService.getGrants(article.authorId);
                                                   ^

TypeError: Cannot read properties of undefined (reading 'getGrants')
    at /Users/m.kutepov/work/nest-commander-bug-example-0/dist/domain/articles/publish-delayed-articles.command.js:28:52
    at Array.forEach (<anonymous>)
    at PublishDelayedArticlesCommand.run (/Users/m.kutepov/work/nest-commander-bug-example-0/dist/domain/articles/publish-delayed-articles.command.js:27:25)
    at Command.<anonymous> (/Users/m.kutepov/work/nest-commander-bug-example-0/node_modules/nest-commander/src/command-runner.service.js:102:54)
    at Command.listener [as _actionHandler] (/Users/m.kutepov/work/nest-commander-bug-example-0/node_modules/nest-commander/node_modules/commander/lib/command.js:482:17)
    at /Users/m.kutepov/work/nest-commander-bug-example-0/node_modules/nest-commander/node_modules/commander/lib/command.js:1264:65
    at Command._chainOrCall (/Users/m.kutepov/work/nest-commander-bug-example-0/node_modules/nest-commander/node_modules/commander/lib/command.js:1158:12)
    at Command._parseCommand (/Users/m.kutepov/work/nest-commander-bug-example-0/node_modules/nest-commander/node_modules/commander/lib/command.js:1264:27)
    at /Users/m.kutepov/work/nest-commander-bug-example-0/node_modules/nest-commander/node_modules/commander/lib/command.js:1062:27
    at Command._chainOrCall (/Users/m.kutepov/work/nest-commander-bug-example-0/node_modules/nest-commander/node_modules/commander/lib/command.js:1158:12)
```

### Expected behavior

The attached repository has another example of missusing a request-module: it has a pseudo-cron-job based on `@nestjs/schedule`, that also indirectly requires request-scoped RolesService. Unlike the Commander module, when I inject a request-scoped provider into a cron-job the scheduler explicitly warns:
```
[Nest] 40731  - 01/26/2023, 1:45:48 AM    WARN [Scheduler] Cannot register cron job "ArticlesCleanupService@handleCron" because it is defined in a non static provider.
```
I think, nest-commander should also at least explicitly throw an error, when it encouters a request-soped provider in command dependencies. Or, it will be better, allow to put a fake `REQUEST` into service container and handle request-scoped services as a common nest app.

### Package

- [X] <code>nest-commander</code>
- [ ] <code>nest-commander-schematics</code>
- [ ] <code>nest-commander-testing</code>

### Package version

2.5.0, 3.4.0

### Node.js version

16.14

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
I'll see about the possibility of overriding Nest's default `REQUEST` token so that a mock non-request scoped provider can be used. If not, I'll add in an error and release that as part of the next release. I'll have to think about the type of release though.

**Comment by jmcdo29** [comment]
From a primitive test, it _looks_ like being able to provide an override of Nest's `REQUEST` is doable. I'm gonna try to extend this out to providing it as a part of the `CommandRunnerModule` that gets created under the hood of the `CommandFactory` so that it's automatically taken care of. Maybe even provide an interface in the `CommandFactory` to pass in a mock request context

**Comment by jmcdo29** [comment]
![image](https://user-images.githubusercontent.com/28268680/214900673-6187356b-1e01-492c-a1f6-3e9249237012.png)

**Comment by jmcdo29** [comment]
Hmm, as it turns out, currently global modules are resolved after internal modules (probably a change that can be made somewhere inside Nest's core code) so the `InternalCoreModule` always resolves the`REQUEST` provider before my `CommandRunnerModule` can. So at the moment, this can be mitigated by providing your own `REQUEST` provider inside the module containing the command, but I don't (yet) have a way to provide a global override when using the module. Looking at updating Nest's code to allow for this though

**Comment by jmcdo29** [comment]
Okay, so there's not much we can do in Nest's code base for this, but I have added in a `try/catch` around the call that gives a nice warning when a (probably) request scoped provider gets used 

![image](https://user-images.githubusercontent.com/28268680/215591864-2fde31a0-e7d2-49ae-aff1-0548172baf50.png)


I've also created a `@RequestModule()` decorator to wrap Nest's standard `@Module()` decorator that you can pass a mock request value to that is singleton so that a mock request can be used and the request scoped provider (so long as it isn't explicitly set to `REQUEST`) can be treated as a singleton in the case of the CLI

**Comment by jmcdo29** [comment]
Added in `nest-commander@3.5.0`
