### ISSUE TITLE
A service tried to call a property of "undefined" error, when trying to access an undefined property

### ISSUE THREAD

**Issue by simplenotezy** [jmcdo29/nest-commander#828]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

`undefined.length` will provide the following error:

```
Exception has occurred: TypeError: Cannot read properties of undefined (reading 'length')

[Nest] 112  - 03/11/2023, 6:57:49 PM   ERROR [CommandRunnerService] A service tried to call a property of "undefined" in the SendNotificationCommand class. Did you use a request scoped provider without the @RequestModule() decorator?
```

### Minimum reproduction code

```ts
import { Command, CommandRunner, Option } from 'nest-commander';
import { LogService } from './log.service';

@Command({ name: 'basic', description: 'A parameter parse' })
export class BasicCommand extends CommandRunner {
  constructor(private readonly logService: LogService) {
    super();
  }

  async run(passedParam: string[], options?: []): Promise<void> {
    const test = {};

    test.hello.world; // will return error
  }
}

```

### Expected behavior

Should return:

    cannot read properties `world` of undefined

### Package

- [X] <code>nest-commander</code>
- [ ] <code>nest-commander-schematics</code>
- [ ] <code>nest-commander-testing</code>

### Package version

3.6.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by simplenotezy** [comment]
I don't think it's necessary. All that is calling: `undefined.someProperty` inside `run` and that error will be shown

**Comment by jmcdo29** [comment]
You provided a code snippet. If you looked at the comment though, I said a "minimum reproduction **repository**". This helps with tracking down the bug, even if it is obvious, **and** helps to build future test cases.

Looks like I should be adding this log and still throwing the original error instead of directly returning [here](https://github.com/jmcdo29/nest-commander/blob/main/packages/nest-commander/src/command-runner.service.ts#L186). I understand that it _simply_ would be calling `undefiend.someProperty` to trigger this error, the idea of this log line it to be _helpful_ in possibly tracing why a service is undefined if that is ever the case. As there's no good way to determine if it's an injected value that is showing up as `undefined`, this was the best solution I could think of.

**Comment by simplenotezy** [comment]
I see! Well yes, I think a good workaround is providing the stacktrace still - that could perhaps solve both issues 😊

**Comment by jmcdo29** [comment]
Yeah, honestly not sure why I _don't_ provide the stack trace
